### ISSUE TITLE
Stops working with Hexchat if you run more than one Hexchat window at the same time.

### ISSUE THREAD

**Issue by mDeaders** [JuliusZet/Fuel-Rats-IRC-Helper#3]
It works fine when all your chats are collapsed into the main window, but completely stops working after you detach one of the channels. 
(Which is a slight shame as I tend to have #fuelrats and #ratchat in seperate windows.)
Otherwise, its fantastic!

**Comment by JuliusZet** [comment]
Hi @mDeaders!
I am a little bit surprised that somebody is actually using this. ;) Thank you for your feedback!
However I am not sure if I will be able to fix the issue you are describing. The IRC Helper is looking for a process with a specific name, which is definable in the settings. But if there are multiple processes with that same name, the tool can not decide which process to choose and focus. :(
Maybe it is possible to add a function that chooses the correct window based on the window title. Do you think that this would help in your case? Please let me know if your separate windows have different window titles.
Best regards.
JuliusZet

**Comment by mDeaders** [comment]
Hey @JuliusZet!

Yeah, funny enough. I was actually just about to sit down and build my own IRC client in python, to do exactly what yours does. And then someone (I cant remember who?) Asked me why reinvent the wheel. :P

I have a few other suggestions id love to share with you directly if you're open to that?
Drop me a message on IRC sometime, I'm hard to miss under the name Deaders. ;)

- Thanks!
Deaders

**Comment by JuliusZet** [comment]
Fixed in version 1.3.0.0
Focusing windows now uses window titles instead of process names.
